color0 #302126
color1 #b63936
color2 #c6869b
color3 #bd8175
color4 #bda575
color5 #d6a8b7
color6 #d6b0a9
color7 #f3f2f2
color8 #776269
color9 #b63936
color10 #c6869b
color11 #bd8175
color12 #bda575
color13 #d6a8b7
color14 #d6b0a9
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #231a1d
background            #231a1d
foreground            #f3f2f2
selection_foreground  #b6afb1
selection_background  #302126
active_border_color   #c6869b
inactive_border_color #302126
url_color             #c6869b

active_tab_foreground   #080607
active_tab_background   #c6869b
inactive_tab_foreground #b6afb1
inactive_tab_background #302126
cursor_trail_color      #b6afb1
