[main]
font=firacode:size=40
prompt="❯ "
layer=overlay
exit-on-keyboard-focus-loss=yes
show-actions=no
fields=name,generic,comment,categories,filename,keywords
# Lines and columns
lines=10
width=35
horizontal-pad=20
vertical-pad=12
inner-pad=8
# Icons
icons-enabled=yes
icon-theme=Papirus
# apps
app-id=games

[border]
width=2
radius=8

[key-bindings]
cancel=Escape Control+c
execute=Return KP_Enter
cursor-left=Left Control+b
cursor-left-word=Control+Left Mod1+b
cursor-right=Right Control+f
cursor-right-word=Control+Right Mod1+f

[colors]
background=23221aCC
text=f2f2f3ff
prompt=d7c475ff
placeholder=bab0cfff
input=d7c475ff
match=bab0cfff
selection=d7c47580
selection-text=f2f2f3ff
selection-match=1b2022ff
counter=b0b6cfff
border=d7c475ff

include=/home/jackson/.config/fuzzel/themes/noctalia
